# Generated by Django 6.0.3 on 2026-03-24 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cabazes', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cabaz',
            name='products',
            field=models.ManyToManyField(blank=True, to='products.product'),
        ),
    ]
