# Generated by Django 6.0.3 on 2026-03-24 10:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='producerproduct',
            name='producer',
            field=models.ForeignKey(limit_choices_to={'user_type': 'producer'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='product',
            name='producers',
            field=models.ManyToManyField(limit_choices_to={'user_type': 'producer'}, through='products.ProducerProduct', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='producerproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product'),
        ),
    ]
